"""Generate configs for N_synthetic sweep.

Trains D variant (real + simple-prompt synth) with varying n_synthetic_per_class
on dinov2_small (cheapest model). Combined with existing n=120 runs, gives
4 data points for the acc(N_synth) plot.
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
EXP_DIR = ROOT / "configs" / "exp"

# n=120 already exists as D_dinov2_small_seed{0,1,2}; sweep adds 30, 60, 240.
N_VALUES = [30, 60, 240]
MODEL = "dinov2_small"
VARIANT = "D"
SEEDS = [0, 1, 2]

HEADER = """# Auto-generated by scripts/generate_sweep_configs.py
# Regenerate: python scripts/generate_sweep_configs.py
"""


def make_config(n_synth: int, seed: int) -> dict:
    run_name = f"{VARIANT}_{MODEL}_n{n_synth}_seed{seed}"
    cfg: dict = {
        "variant": VARIANT,
        "seed": seed,
        "run_name": run_name,
        "data": {
            "splits_path": f"data/splits/pets_10cls_30perclass_seed{seed}.json",
            "synthetic_root": f"data/synthetic/variant_{VARIANT}",
            "n_synthetic_per_class": n_synth,
            "synthetic_manifest": f"data/synthetic/variant_{VARIANT}/manifest_kept.csv",
        },
        "model": {"name": MODEL, "pretrained": True},
        "augmentation": {"mode": "none"},
        # dinov2_small uses higher LR (linear probe)
        "training": {"learning_rate": 0.001},
    }
    return cfg


def main() -> None:
    EXP_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for n_synth in N_VALUES:
        for seed in SEEDS:
            cfg = make_config(n_synth, seed)
            path = EXP_DIR / f"{cfg['run_name']}.yaml"
            yaml_str = yaml.dump(cfg, sort_keys=False, default_flow_style=False)
            with open(path, "w") as f:
                f.write(HEADER + "\n" + yaml_str)
            written.append(path.name)

    print(f"Generated {len(written)} sweep configs in {EXP_DIR.relative_to(ROOT)}/")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
