"""Generator configow eksperymentow dla fazy 2 (warianty A i B).

Produkuje 4 modele x 2 warianty x 3 seedy = 24 configi w configs/exp/.

Uruchomienie:
    python scripts/generate_configs.py

Pliki sa nadpisywane idempotentnie. Header informuje ze to auto-gen.
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
EXP_DIR = ROOT / "configs" / "exp"

MODELS = ["resnet18", "convnext_tiny", "deit_tiny", "dinov2_small"]

# variant -> augmentation.mode
VARIANTS: dict[str, str] = {
    "A": "none",       # tylko dane realne
    "B": "classical",  # realne + RandAugment
}

SEEDS = [0, 1, 2]

# Per-model nadpisania (np. wyzsze LR dla DINOv2 linear probe)
MODEL_OVERRIDES: dict[str, dict] = {
    "dinov2_small": {
        # Backbone zamrozony, trenuje tylko glowica liniowa -> wyzsze LR ok
        "training": {"learning_rate": 0.001},
    },
}

HEADER = """# Auto-generated by scripts/generate_configs.py
# Regenerate: python scripts/generate_configs.py
"""


def make_config(variant: str, model: str, seed: int) -> dict:
    run_name = f"{variant}_{model}_seed{seed}"
    cfg: dict = {
        "variant": variant,
        "seed": seed,
        "run_name": run_name,
        "data": {
            "splits_path": f"data/splits/pets_10cls_30perclass_seed{seed}.json",
        },
        "model": {
            "name": model,
            "pretrained": True,
        },
        "augmentation": {
            "mode": VARIANTS[variant],
        },
    }
    if model in MODEL_OVERRIDES:
        for key, val in MODEL_OVERRIDES[model].items():
            cfg[key] = val
    return cfg


def write_config(path: Path, cfg: dict) -> None:
    yaml_str = yaml.dump(cfg, sort_keys=False, default_flow_style=False)
    with open(path, "w") as f:
        f.write(HEADER + "\n")
        f.write(yaml_str)


def main() -> None:
    EXP_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for variant in VARIANTS:
        for model in MODELS:
            for seed in SEEDS:
                cfg = make_config(variant, model, seed)
                path = EXP_DIR / f"{cfg['run_name']}.yaml"
                write_config(path, cfg)
                written.append(path.name)

    print(f"Generated {len(written)} configs in {EXP_DIR.relative_to(ROOT)}/")
    for name in written:
        print(f"  {name}")


if __name__ == "__main__":
    main()
